
name: 'cms_aalr_connector'
version: '1.0.0'

profile: 'cms_aalr_connector'

vars:
  input_database: mssp_duckdb
  input_schema: raw_data

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

