
name: 'cms_aalr_connector'
version: '0.1.0'

profile: 'default'

vars:
  input_database: tuva
  input_schema: raw_data
  demo_data_only: false

  claims_enabled: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
   cms_aalr_connector:
     final:
       +materialized: table
     intermediate:
       +materialized: table
     staging:
       +materialized: view

