vbca:
  target: dev
  outputs:
    dev:
      type: snowflake
      database: VBCA_TUVA_DEV
      schema: TUVA_DBT
      warehouse: TUVA_WH
      role: TUVA
    prod:
      type: snowflake
      database: VBCA_TUVA
      schema: TUVA_DBT
      warehouse: TUVA_WH
      role: TUVA