vbca:
  target: dev
  outputs:
    dev:
      type: snowflake
      database: VBCA_TUVA_DEV
      schema: TUVA_WH
      warehouse: VBCA_DBT_WH
      role: TUVA_FULL
    prod:
      type: snowflake
      database: VBCA_TUVA
      schema: TUVA_WH
      warehouse: VBCA_DBT_WH
      role: TUVA_FULL