vbca:
  target: dev
  outputs:
    dev:
      type: snowflake
      database: VBCA_TUVA_DEV
      schema: MIKE_DBT
      warehouse: TUVA_WH
      role: TUVA
      threads: 8
      query_tag: dbt
    prod:
      type: snowflake
      database: VBCA_TUVA
      schema: MIKE_DBT
      warehouse: TUVA_WH
      role: TUVA
      threads: 8
      query_tag: dbt