SELECT
    cast(bene_mbi_id as {{ dbt.type_string() }}) as bene_mbi_id,
    cast(bene_hic_num as {{ dbt.type_string() }}) as bene_hic_num,
    cast(bene_1st_name as {{ dbt.type_string() }}) as bene_1st_name,
    cast(bene_last_name as {{ dbt.type_string() }}) as bene_last_name,
    cast(bene_sex_cd as {{ dbt.type_string() }}) as bene_sex_cd,
    {{ try_to_cast_date("bene_brth_dt", "MM/DD/YYYY") }} as bene_brth_dt,
    {{ try_to_cast_date("bene_death_dt", "MM/DD/YYYY") }} as bene_death_dt,
    cast(geo_ssa_cnty_cd_name as {{ dbt.type_string() }}) as geo_ssa_cnty_cd_name,
    cast(geo_ssa_state_name as {{ dbt.type_string() }}) as geo_ssa_state_name,
    cast(state_county_cd as {{ dbt.type_string() }}) as state_county_cd,
    cast(in_va_max as integer) as in_va_max,
    cast(va_tin as {{ dbt.type_string() }}) as va_tin,
    cast(va_npi as {{ dbt.type_string() }}) as va_npi,
    cast(cba_flag as integer) as cba_flag,
    cast(assignment_type as integer) as assignment_type,
    cast(assigned_before as integer) as assigned_before,
    cast(asg_status as {{ dbt.type_string() }}) as asg_status,
    cast(partd_months as integer) as partd_months,
    cast(enrollflag1 as integer) as enrollflag1,
    cast(enrollflag2 as integer) as enrollflag2,
    cast(enrollflag3 as integer) as enrollflag3,
    cast(enrollflag4 as integer) as enrollflag4,
    cast(enrollflag5 as integer) as enrollflag5,
    cast(enrollflag6 as integer) as enrollflag6,
    cast(enrollflag7 as integer) as enrollflag7,
    cast(enrollflag8 as integer) as enrollflag8,
    cast(enrollflag9 as integer) as enrollflag9,
    cast(enrollflag10 as integer) as enrollflag10,
    cast(enrollflag11 as integer) as enrollflag11,
    cast(enrollflag12 as integer) as enrollflag12,
    cast(hcc_version as {{ dbt.type_string() }}) as hcc_version,
    cast(hcc_col_1 as integer) as hcc_col_1,
    cast(hcc_col_2 as integer) as hcc_col_2,
    cast(hcc_col_3 as integer) as hcc_col_3,
    cast(hcc_col_4 as integer) as hcc_col_4,
    cast(hcc_col_5 as integer) as hcc_col_5,
    cast(hcc_col_6 as integer) as hcc_col_6,
    cast(hcc_col_7 as integer) as hcc_col_7,
    cast(hcc_col_8 as integer) as hcc_col_8,
    cast(hcc_col_9 as integer) as hcc_col_9,
    cast(hcc_col_10 as integer) as hcc_col_10,
    cast(hcc_col_11 as integer) as hcc_col_11,
    cast(hcc_col_12 as integer) as hcc_col_12,
    cast(hcc_col_13 as integer) as hcc_col_13,
    cast(hcc_col_14 as integer) as hcc_col_14,
    cast(hcc_col_15 as integer) as hcc_col_15,
    cast(hcc_col_16 as integer) as hcc_col_16,
    cast(hcc_col_17 as integer) as hcc_col_17,
    cast(hcc_col_18 as integer) as hcc_col_18,
    cast(hcc_col_19 as integer) as hcc_col_19,
    cast(hcc_col_20 as integer) as hcc_col_20,
    cast(hcc_col_21 as integer) as hcc_col_21,
    cast(hcc_col_22 as integer) as hcc_col_22,
    cast(hcc_col_23 as integer) as hcc_col_23,
    cast(hcc_col_24 as integer) as hcc_col_24,
    cast(hcc_col_25 as integer) as hcc_col_25,
    cast(hcc_col_26 as integer) as hcc_col_26,
    cast(hcc_col_27 as integer) as hcc_col_27,
    cast(hcc_col_28 as integer) as hcc_col_28,
    cast(hcc_col_29 as integer) as hcc_col_29,
    cast(hcc_col_30 as integer) as hcc_col_30,
    cast(hcc_col_31 as integer) as hcc_col_31,
    cast(hcc_col_32 as integer) as hcc_col_32,
    cast(hcc_col_33 as integer) as hcc_col_33,
    cast(hcc_col_34 as integer) as hcc_col_34,
    cast(hcc_col_35 as integer) as hcc_col_35,
    cast(hcc_col_36 as integer) as hcc_col_36,
    cast(hcc_col_37 as integer) as hcc_col_37,
    cast(hcc_col_38 as integer) as hcc_col_38,
    cast(hcc_col_39 as integer) as hcc_col_39,
    cast(hcc_col_40 as integer) as hcc_col_40,
    cast(hcc_col_41 as integer) as hcc_col_41,
    cast(hcc_col_42 as integer) as hcc_col_42,
    cast(hcc_col_43 as integer) as hcc_col_43,
    cast(hcc_col_44 as integer) as hcc_col_44,
    cast(hcc_col_45 as integer) as hcc_col_45,
    cast(hcc_col_46 as integer) as hcc_col_46,
    cast(hcc_col_47 as integer) as hcc_col_47,
    cast(hcc_col_48 as integer) as hcc_col_48,
    cast(hcc_col_49 as integer) as hcc_col_49,
    cast(hcc_col_50 as integer) as hcc_col_50,
    cast(hcc_col_51 as integer) as hcc_col_51,
    cast(hcc_col_52 as integer) as hcc_col_52,
    cast(hcc_col_53 as integer) as hcc_col_53,
    cast(hcc_col_54 as integer) as hcc_col_54,
    cast(hcc_col_55 as integer) as hcc_col_55,
    cast(hcc_col_56 as integer) as hcc_col_56,
    cast(hcc_col_57 as integer) as hcc_col_57,
    cast(hcc_col_58 as integer) as hcc_col_58,
    cast(hcc_col_59 as integer) as hcc_col_59,
    cast(hcc_col_60 as integer) as hcc_col_60,
    cast(hcc_col_61 as integer) as hcc_col_61,
    cast(hcc_col_62 as integer) as hcc_col_62,
    cast(hcc_col_63 as integer) as hcc_col_63,
    cast(hcc_col_64 as integer) as hcc_col_64,
    cast(hcc_col_65 as integer) as hcc_col_65,
    cast(hcc_col_66 as integer) as hcc_col_66,
    cast(hcc_col_67 as integer) as hcc_col_67,
    cast(hcc_col_68 as integer) as hcc_col_68,
    cast(hcc_col_69 as integer) as hcc_col_69,
    cast(hcc_col_70 as integer) as hcc_col_70,
    cast(hcc_col_71 as integer) as hcc_col_71,
    cast(hcc_col_72 as integer) as hcc_col_72,
    cast(hcc_col_73 as integer) as hcc_col_73,
    cast(hcc_col_74 as integer) as hcc_col_74,
    cast(hcc_col_75 as integer) as hcc_col_75,
    cast(hcc_col_76 as integer) as hcc_col_76,
    cast(hcc_col_77 as integer) as hcc_col_77,
    cast(hcc_col_78 as integer) as hcc_col_78,
    cast(hcc_col_79 as integer) as hcc_col_79,
    cast(hcc_col_80 as integer) as hcc_col_80,
    cast(hcc_col_81 as integer) as hcc_col_81,
    cast(hcc_col_82 as integer) as hcc_col_82,
    cast(hcc_col_83 as integer) as hcc_col_83,
    cast(hcc_col_84 as integer) as hcc_col_84,
    cast(hcc_col_85 as integer) as hcc_col_85,
    cast(hcc_col_86 as integer) as hcc_col_86,
    cast(hcc_col_87 as integer) as hcc_col_87,
    cast(hcc_col_88 as integer) as hcc_col_88,
    cast(hcc_col_89 as integer) as hcc_col_89,
    cast(hcc_col_90 as integer) as hcc_col_90,
    cast(hcc_col_91 as integer) as hcc_col_91,
    cast(hcc_col_92 as integer) as hcc_col_92,
    cast(hcc_col_93 as integer) as hcc_col_93,
    cast(hcc_col_94 as integer) as hcc_col_94,
    cast(hcc_col_95 as integer) as hcc_col_95,
    cast(hcc_col_96 as integer) as hcc_col_96,
    cast(hcc_col_97 as integer) as hcc_col_97,
    cast(hcc_col_98 as integer) as hcc_col_98,
    cast(hcc_col_99 as integer) as hcc_col_99,
    cast(hcc_col_100 as integer) as hcc_col_100,
    cast(hcc_col_101 as integer) as hcc_col_101,
    cast(hcc_col_102 as integer) as hcc_col_102,
    cast(hcc_col_103 as integer) as hcc_col_103,
    cast(hcc_col_104 as integer) as hcc_col_104,
    cast(hcc_col_105 as integer) as hcc_col_105,
    cast(hcc_col_106 as integer) as hcc_col_106,
    cast(hcc_col_107 as integer) as hcc_col_107,
    cast(hcc_col_108 as integer) as hcc_col_108,
    cast(hcc_col_109 as integer) as hcc_col_109,
    cast(hcc_col_110 as integer) as hcc_col_110,
    cast(hcc_col_111 as integer) as hcc_col_111,
    cast(hcc_col_112 as integer) as hcc_col_112,
    cast(hcc_col_113 as integer) as hcc_col_113,
    cast(hcc_col_114 as integer) as hcc_col_114,
    cast(hcc_col_115 as integer) as hcc_col_115,
    cast(hcc_col_116 as integer) as hcc_col_116,
    cast(hcc_col_117 as integer) as hcc_col_117,
    cast(hcc_col_118 as integer) as hcc_col_118,
    cast(hcc_col_119 as integer) as hcc_col_119,
    cast(hcc_col_120 as integer) as hcc_col_120,
    {{ cast_numeric('bene_rsk_r_scre_01') }} as bene_rsk_r_scre_01,
    {{ cast_numeric('bene_rsk_r_scre_02') }} as bene_rsk_r_scre_02,
    {{ cast_numeric('bene_rsk_r_scre_03') }} as bene_rsk_r_scre_03,
    {{ cast_numeric('bene_rsk_r_scre_04') }} as bene_rsk_r_scre_04,
    {{ cast_numeric('bene_rsk_r_scre_05') }} as bene_rsk_r_scre_05,
    {{ cast_numeric('bene_rsk_r_scre_06') }} as bene_rsk_r_scre_06,
    {{ cast_numeric('bene_rsk_r_scre_07') }} as bene_rsk_r_scre_07,
    {{ cast_numeric('bene_rsk_r_scre_08') }} as bene_rsk_r_scre_08,
    {{ cast_numeric('bene_rsk_r_scre_09') }} as bene_rsk_r_scre_09,
    {{ cast_numeric('bene_rsk_r_scre_10') }} as bene_rsk_r_scre_10,
    {{ cast_numeric('bene_rsk_r_scre_11') }} as bene_rsk_r_scre_11,
    {{ cast_numeric('bene_rsk_r_scre_12') }} as bene_rsk_r_scre_12,
    {{ cast_numeric('esrd_score') }} as esrd_score,
    {{ cast_numeric('dis_score') }} as dis_score,
    {{ cast_numeric('agdu_score') }} as agdu_score,
    {{ cast_numeric('agnd_score') }} as agnd_score,
    {{ cast_numeric('dem_esrd_score') }} as dem_esrd_score,
    {{ cast_numeric('dem_dis_score') }} as dem_dis_score,
    {{ cast_numeric('dem_agdu_score') }} as dem_agdu_score,
    {{ cast_numeric('dem_agnd_score') }} as dem_agnd_score,
    cast(new_enrollee as integer) as new_enrollee,
    cast(lti_status as integer) as lti_status,
    cast(bene_race_cd as integer) as bene_race_cd,
    {{ cast_numeric('bene_psnyrs_dual') }} as bene_psnyrs_dual,
    cast(directory_name as {{ dbt.type_string() }}) as directory_name,
    cast(file_name as {{ dbt.type_string() }}) as file_name,
    {{ extract_file_metadata() }}
FROM {{ source("cms_ssp_reports", "aalr1_assigned_beneficiaries")}} b